<?php
namespace Genealogy;
use \PDO;
use \Exception;
use \Templating\Template;
require_once __NAMESPACE__ . '/common.inc';
require_once __NAMESPACE__ . '/Location.inc';
$location	= new Location(array('location' => "Cabbagetown, Toronto, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Cabot, Sudbury District, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Cache Bay, Springer, Nipissing District, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Cache Lake, Canisbay, Nipissing District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Cadeau, Cadeau Township, Algoma District, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caderette, Springer, Nipissing District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Cadmus, Cartwright, Durham, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caen, Sudbury District, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Caesarea, Cartwright, Durham, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Cahill Dr, Sandwich South, Essex, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Cahore, Finch, Stormont, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Cainsville, Brantford, Brant, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Caintown, Front of Yonge, Leeds & Grenville, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Cairngorm, Metcalfe & Caradoc, Middlesex, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Cairo, Euphemia, Lambton, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Cairo, Timiskaming District, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Caistor Centre, Caistor, Lincoln, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caistor, Lincoln, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Caistorville, Caistor, Lincoln, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caithness, Cochrane District, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Calabogie, Bagot, Renfrew, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Calais, Sudbury District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Calamity Gulch, Dymond, Timiskaming District, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Calder, Cochrane District, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Calderwood, Normanby, Grey, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caldwell, Nipissing District, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Caledon, Albion, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caledon East, Albion, Peel, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Caledon, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caledon Village, Albion, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Caledonia, Seneca, Haldimand, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caledonia, Prescott, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Caledonia Front, Caledonia, Prescott, ON, CA"));
$location->save(true);
$location	= new Location(array('location' => "Caledonia Springs, Caledonia, Prescott, ON, CA"));
$location['notes']  = 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Caledonia, Caledonia Township, Prescott and Russell, ON, CA"));
$location->save(true);
