<?php
namespace Genealogy;
use \PDO;
use \Exception;
use \Templating\Template;
require_once __NAMESPACE__ . '/common.inc';
require_once __NAMESPACE__ . '/Location.inc';
$location	= new Location(array('location'	=> "Abraham Head, Wolfe Island, Frontenac, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Abraham, Algoma District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Abram Lake, Studholme, Cochrane District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Abram Lake, Drayton, Kenora District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Abram Rapids, Drayton, Kenora District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Abrams Lake, Blount, Cochrane District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Abrams Point, Cardiff, Haliburton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Abrey Island, Thunder Bay District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Abrey, Thunder Bay District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Admaston/Bromley, Renfrew, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Allbright Lake, Thunder Bay District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Ambrose, North Walsingham, Norfolk, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Ambrose Lake, 33-XXVI, Algoma District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Armbro Heights, Chinguacousy, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Aubrey, Hong Kong, Sudbury District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Aubrey Island, Leeds & Grenville United Counties, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Aubrey, Kenora District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Baldwins Bridge, Mountain, Dundas, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Burgess, Sherbrooke, Lanark, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bear Brook Station, Cumberland, Carleton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bearbrook, Cumerland, Russell, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Becketts Bridge, Wainfleet, Welland, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Benbrook, Billing's Bridge, Gloucester, Carleton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Binbrook, Binbrook, Wentworth, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Binbrook, Wentworth, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Black River Bridge, South Marysburgh, Prince Edward, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bolingbroke, South Sherbrooke, Lanark, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bracci, Algoma District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bracebridge, Macaulay, Muskoka District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brackenrig, Muskoka District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brackin, Sudbury District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bracondale, York, York, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradburn, Cochrane District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bradens Bay, Oro, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradette, Cochrane District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bradford, West Gwillimbury, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradford West Gwillimbury, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradley, Greenock, Bruce, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradley, Dover, Kent, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradley Creek, South Plantagenet, Prescott, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradley, Cochrane District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bradshaw, Sombra, Lambton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradshaw, Bedford, Frontenac, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bradshaw, Kenora District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bradyville, Alfred, Prescott and Russell United Counties, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Braeheid, East Flamborough, Wentworth, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Braemar, West Zorra, Oxford, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Braeside, McNab, Renfrew, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bragg, Cochrane District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brain, Cochrane District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Braithwaite, Sudbury District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bramalea, Chinguacousy, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bramley, Innisfil, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brampton, Chinguacousy, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Branchton, North Dumfries, Waterloo, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brander Park, Sombra, Lambton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brandy Creek, Windham, Norfolk, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brandy Point, Fullarton, Perth, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brant County, Ontario (Province of) Brant North, Brant, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brant South, Brant, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brant, Bruce, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brant's Ford, Brantford, Brant, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brantford, Brantford, Brant, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brantford, Brant, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brawny, Barron, Nipissing District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bray, Osgoode, Carleton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bray Lake, Machar, Parry Sound District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bray, Algoma District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brayton, Wellington, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Breadalbane, Lochiel, Glengarry, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Breadner, Sudbury District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brebeuf, Sudbury District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brechin, Mara, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brechin Beach, Mara, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brechin Point, Mara, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Breckenridge, Algoma District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Breezy's Corners, East Flamborough, Wentworth, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Breithaupt, Kenora District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bremner,, 70 Thunder Bay District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brenbrook, Brent, Deacon, Nipissing District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brentha, Dack, Timiskaming District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brentwood, Sunnidale, Simcoe, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Breslau, Waterloo, Waterloo, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brethour, Brethour, Timiskaming District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brethour, Timiskaming District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brewer Lake, Storrington, Frontenac, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brewer's Upper Mills, Pittsburgh, Frontenac, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brewers Mills, Pittsburgh, Frontenac, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brewster, Bosanquet, Lambton, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Briars Park, Georgina, York, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brickley, Percy, Northumberland, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridge End, Lancaster, Glengarry, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridge End, Harwich, Kent, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridgeburg, Bertie, Welland, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridgenorth, Smith, Peterborough, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridgeport, Waterloo, Waterloo, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridgeport, Louth Lincoln, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridges, Kenora District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bridgewater, Thurlow, Hastings, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridgewater, Elzevir, Hastings, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridgewater, Goderich, Huron, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bridgland, Algoma District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brier Hill, South Crosby & Rear of Leeds and Lansdowne, Leeds, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brigden, Moore, Lambton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Briggs, Nipissing District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Bright, Blandford, Oxford, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bright, Algoma District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brighton, Brighton, Northumberland, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brighton Beach, North Gwillimbury, York, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brighton, Northumberland, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brights Grove, Sarnia, Lambton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brightside, Darling, & Lanark, Lanark, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brignall, Conger, Parry Sound District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brigstocke, Timiskaming District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brimacombe, Algoma District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brimstone, Caledon, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brinklow, Limerick, Hastings, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brinkman Corners, Lindsay, Bruce, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brinkworth, Rawdon, Hastings, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brinsley, McGillivray, Middlesex, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brinston, Matilda, Dundas, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brinston's Corners, Matilda, Dundas, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brisbane, Erin, Wellington, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brisson, Russell, Russell, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Bristol, Cochrane District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Britainville, Campbell, Manitoulin District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britannia, Nepean, Carleton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britannia, Franklin, Muskoka District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britannia, Toronto, Peel, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britannia Bay, Nepean, Carleton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britanniaville, Nepean, Carleton, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britt, Henvey, & Wallbridge, Parry Sound District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britton, Elma, Perth, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Britton, Kenora District, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Broadbent, McKellar, Parry Sound District, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Broadville, Tyendinaga, Hastings, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brock District, Brock Island, Leeds & Frontenac Counties, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brock Road, Pickering, Ontario, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brock Road, Puslinch, Wellington, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> " Brock, Ontario, ON, CA"));
$location['notes']	= 'Township';
$location->save(true);
$location	= new Location(array('location'	=> "Brockley, London, Middlesex, ON, CA"));
$location->save(true);
$location	= new Location(array('location'	=> "Brocks Beach, Nottawasaga, Simcoe, ON, CA"));
$location->save(true);
